<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class IngredientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('ingredients')->insert([
            ['name' => 'spaghetti'],
            ['name' => 'vegetable oil'],
            ['name' => 'scallops'],
            ['name' => 'butter'],
            ['name' => 'garlic'],
            ['name' => 'lemon zest'],
            ['name' => 'red pepper flakes'],
            ['name' => 'dry sherry'],
            ['name' => 'heavy cream'],
            ['name' => 'salt'],
            ['name' => 'pepper'],
            ['name' => 'lemon'],
            ['name' => 'italian parsley'],
            ['name' => 'parmigiano-reggiano cheese'],
            ['name' => 'tuna'],
            ['name' => 'mayonnaise'],
            ['name' => 'celery'],
            ['name' => 'onion'],
            ['name' => 'fresh parsley'],
            ['name' => 'lemon juice'],
            ['name' => 'garlic powder'],
            ['name' => 'ground black pepper'],
            ['name' => 'paprika'],
            ['name' => 'fresh ginger'],
            ['name' => 'red curry paste'],
            ['name' => 'lemon grass'],
            ['name' => 'chicken broth'],
            ['name' => 'fish sauce'],
            ['name' => 'light brown sugar'],
            ['name' => 'coconut milk'],
            ['name' => 'fresh shiitake mushrooms'],
            ['name' => 'medium shrimp'],
            ['name' => 'fresh lime juice'],
            ['name' => 'fresh cilantro'],
            ['name' => 'chicken thighs'],
            ['name' => 'pork fat or fatty bacon'],
            ['name' => 'fresh French breadcrumbs'],
            ['name' => 'sautéed onions'],
            ['name' => 'egg'],
            ['name' => 'white wine'],
            ['name' => 'parsley'],
            ['name' => 'kosher salt'],
            ['name' => 'freshly ground black pepper'],
            ['name' => 'chili flakes'],
            ['name' => 'fennel seeds'],
            ['name' => 'prepared tomato sauce'],
            ['name' => 'Dijon mustard'],
            ['name' => 'honey'],
            ['name' => 'dry bread crumbs'],
            ['name' => 'pecans'],
            ['name' => 'fillets salmon'],
            ['name' => 'sesame oil'],
            ['name' => 'olive oil'],
            ['name' => 'uncooked medium shrimp'],
            ['name' => 'frozen peas and carrots'],
            ['name' => 'frozen corn'],
            ['name' => 'cooked rice'],
            ['name' => 'green onions'],
            ['name' => 'low-sodium soy sauce'],
            ['name' => 'cooking oil'],
            ['name' => 'chicken legs and thighs'],
            ['name' => 'squash'],
            ['name' => 'bok choy'],
            ['name' => 'fresh spinach'],
            ['name' => 'sweet Italian sausage'],
            ['name' => 'yellow onion'],
            ['name' => 'red onion'],
            ['name' => 'red bell pepper'],
            ['name' => 'green bell pepper'],
            ['name' => 'dried basil'],
            ['name' => 'dried oregano'],
            ['name' => 'curry powder'],
            ['name' => 'ground cinnamon'],
            ['name' => 'bay leaf'],
            ['name' => 'fresh ginger root'],
            ['name' => 'white sugar'],
            ['name' => 'chicken breast halves'],
            ['name' => 'tomato paste'],
            ['name' => 'plain yogurt'],
            ['name' => 'cayenne pepper'],
            ['name' => 'spicy Italian sausages'],
            ['name' => 'low-sodium chicken broth'],
            ['name' => 'orecchiette pasta'],
            ['name' => 'arugula'],
            ['name' => 'soy sauce'],
            ['name' => 'onion powder'],
            ['name' => 'elbow macaroni'],
            ['name' => 'salted butter'],
            ['name' => 'all-purpose flour'],
            ['name' => 'milk'],
            ['name' => 'Cheddar cheese'],
            ['name' => 'Parmesan cheese'],
            ['name' => 'hot dog bun'],
            ['name' => 'hot dog'],
            ['name' => 'beef stew meat'],
            ['name' => 'beef broth'],
            ['name' => 'carrots'],
            ['name' => 'potatoes'],
            ['name' => 'Worcestershire sauce'],
            ['name' => 'lean ground beef'],
            ['name' => 'tomatoes'],
            ['name' => 'water'],
            ['name' => 'dried basil leaves'],
            ['name' => 'Italian seasoning'],
            ['name' => 'lasagna noodles'],
            ['name' => 'ricotta cheese'],
            ['name' => 'mozzarella cheese'],
            ['name' => 'beef brisket with spice packet'],
            ['name' => 'red potatoes'],
            ['name' => 'head cabbage'],
            ['name' => 'ketchup'],
            ['name' => 'yellow mustard'],
            ['name' => 'hamburger buns'],
            ['name' => 'dried rosemary'],
            ['name' => 'boneless pork loin roast'],
            ['name' => 'panko bread crumbs'],
            ['name' => 'fresh mozzarella'],
            ['name' => 'fresh basil'],
            ['name' => 'provolone cheese'],
            ['name' => 'dry fettuccine noodles'],
            ['name' => 'sea scallops'],
            ['name' => 'half-and-half cream'],
            ['name' => 'cornstarch'],
            ['name' => 'dark beer'],
            ['name' => 'cod fillets'],
            ['name' => 'corn tortillas'],
            ['name' => 'salsa'],
            ['name' => 'lime'],
        ]);
    }
}